version: '3.8'

services:
  frontend:
    build:
      context: ./reactfrontend      # The directory for the frontend
      dockerfile: Dockerfile
      args:
      - VITE_API_URL=http://127.0.0.1:5000
    ports:
      - "80:80"  # Expose the frontend on port 3000
    networks:
      - app-network
    volumes:
      - ./reactfrontend:/app/src

  backend:
    build:
      context: ./FlaskBackend      # The directory for the backend
      dockerfile: Dockerfile   # The name of the Dockerfile in the backend directory
    ports:
      - "5000:5000"  # Expose the backend on port 5000
    environment:
      - CLIENT_SECRET=${CLIENT_SECRET}  # Reference environment variables
      - CLIENT_ID=${CLIENT_ID}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge



